from enum import Enum

class Intent(str, Enum):
    PROFILE_QUERY = "PROFILE_QUERY"
    LAND_QUERY = "LAND_QUERY"
    CROP_QUERY = "CROP_QUERY"
    INVENTORY_QUERY = "INVENTORY_QUERY"

    WEATHER_QUERY = "WEATHER_QUERY"
    MARKET_QUERY = "MARKET_QUERY"

    SCHEME_QUERY = "SCHEME_QUERY"

    DISEASE_QUERY = "DISEASE_QUERY"
    PEST_QUERY = "PEST_QUERY"
    FERTILIZER_QUERY = "FERTILIZER_QUERY"
    SOIL_HEALTH_QUERY = "SOIL_HEALTH_QUERY"

    FARMING_TIPS_QUERY = "FARMING_TIPS_QUERY"

    GENERAL_AGRICULTURE_QUERY = "GENERAL_AGRICULTURE_QUERY"

    UNKNOWN = "UNKNOWN"
